# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "LedgerFest 2022"
email: "blockchain@columbia.edu"
description: "LedgerFest is B@C's annual crypto conference."
baseurl: ""
url: "https://ledgerfest.info"
permalink: "/blog/:title"

# Organizer Info
organizerName: "B@C"
organizerAlternateName: "Blockchain at Columbia"
organizerDescription: "Student-run blockchain org at Columbia University."
organizerEmail: "blockchain@columbia.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://blockchainatcolumbia.org/"

# Head
metaKeywords: "blockchain, conference,LedgerFest,Web3,Crypto"
twitterAccount: "@BlockchainatCU"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcTelegram: "/img/seo/sharing-telegram.png"

# Documents
c4pUrl: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537"
c4sponsorsUrl: "https://docs.google.com/forms/d/e/1FAIpQLSc-r8W_dozgM3taer0Vq_dwYBHOhsPGyE7e2cuLdAmJI6vN-A/viewform?usp=sf_link"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/faq/", text: "FAQ"}
 - {permalink: "/team/", text: "Organizing Team"}

bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537", text: "Register"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537", text: "Register"}

# Hero Block
heroImage: "Ledgerfest blue.jpeg"
heroTitle: "LedgerFest <typeout>"
eventDate: "September 23rd"
typeoutTextValues: '"", "2022"'
typeoutFallback: "2022"
heroButtons:
 - {link: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537", text: "Register"}
# About Block
aboutTitle: "About LedgerFest"
aboutBlock:
 - {title: "Conference", image: "conf.jpg", text: "LedgerFest is Blockchain@Columbia's annual crypto conference. We aim to educate and inspire students and the broader community through fireside chats, talks, and tutorials from founders and operators of the leading protocols and investors in the space." }
 - {title: "Topics", image: "hackathon2.jpg", text: "DeFi, web3, layer 1/layer2 research and protocols, NFTs, crypto gaming, humanitarian and political impact of blockchains, and more." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1", specialCharacter: "", info: "days", detail: ""}
 - {count: "25", specialCharacter: "+", info: "speakers", detail: ""}

# Rockstar Speakers Block
rockstarSpeakersImage: "background2.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Gather"
eventLocationLink: "http://www.columbia.edu/cu/computinghistory/pupin.html"
# eventStreetAddress: ""
# eventAddressLocality: ""
# eventAddressLocalityRegion: ""
eventPostalCode: "10027"
eventAddressCountry: "U.S"
eventStartTime: "2021-10-22T10:00"
eventDoorTime: "08:45"
eventEndTime: "2021-10-23T19:45"
eventPlaceCoordinates: "40.809984, -73.961386"
mapCenterCoordinates: "40.809984, -73.961386"
mapMobileCenterCoordinates: "40.809984, -73.961386"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "One-Liberty-Plaza-Breakout.jpeg"
venueSmallImage1: "One-Liberty-Plaza-2nd-Floor-North-Boardroom.jpeg"
venueSmallImage2: "One-Liberty-Plaza-Gallery.jpeg"
venueSmallImage3: "Convene-New-York-City-One-Liberty-Plaza-2nd-Floor-Forum__3_.jpeg"
venueTitle: "Convene One Liberty Plaza"
venueFeatures: ["All Rooms", "<a href='https://www.google.com/maps/place/Convene/@40.7097922,-74.012662,17z/data=!3m2!4b1!5s0x89c25a40d1d8cffd:0x1b2be545314073bc!4m5!3m4!1s0x89c25b11ecd74629:0x1e46d18843e5070f!8m2!3d40.7097922!4d-74.0104733' target='_blank'>1 Liberty St, New York, NY 10006</a>"] 



# Tweets Feed Block
tweetsFeedImage: "EmpireSkyline.jpeg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "ledgerfest22"

# Partners Block
organizersTitle: "Organizer"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a Sponsor"
buyButtonLink: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: ""
ticketsOffers:

 -
  name: "Industry Ticket"
  price: "350"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537"
  buyButtonText: "Buy Now"
 -
  name: "Columbia Alumi/Affilates"
  price: "100"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537"
  buyButtonText: "Buy Now"
 -
  name: "Refundable Student Ticket<> Columbia and NYU"
  price: "20"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537"
  buyButtonText: "Buy Now"
  additionalInfo: "*Requires a valid student ID at the conference check in. Without a student ID, ticket will be cancelled without refund*"

# Footer
socialLinks:
 - {link: "https://www.instagram.com/blockchaincolumbia/", icon: "linkedin"}
 - {link: "https://twitter.com/blockchainatcu?lang=en", icon: "twitter"}
 - {link: "https://www.facebook.com/BlockchainatColumbia/?ref=bookmarks", icon: "facebook"}
 - {link: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537", icon: "rss"}
 - {link: "https://blockchainatcolumbia.org/", icon: "site"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.eventbrite.com/e/ledgerfest22-tickets-401463968537", text: "Evenbrite - LedgerFest Tickets"}
   - {link: "https://blockchainatcolumbia.org/", text: "Blockchain@Columbia"}
   - {link: "https://www.google.com/maps/place/Convene/@40.7097922,-74.012662,17z/data=!3m2!4b1!5s0x89c25a40d1d8cffd:0x1b2be545314073bc!4m5!3m4!1s0x89c25b11ecd74629:0x1e46d18843e5070f!8m2!3d40.7097922!4d-74.0104733", text: "Map"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:blockchain@columbia.edu", text: "blockchain@columbia.edu"}
 -
  title: "FAQ"
  links:
   - {permalink: "/faq/", text: "Frequently Asked Questions"}
# Team Block
teamBlockTitle: "About us"
aboutUs: "Welcome to Blockchain At Columbia, Columbia’s student-run Blockchain club. We are a registered non-profit and aim to facilitate an environment where students can engage with ideas in blockchain, developing into the leading minds of web3, and making some friends along the way. We are governed by Lion DAO, the first student DAO launched last summer."

# Speakers List Block
showSessions: true
