# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "LedgerFest 2020"
email: "blockchain@columbia.edu"
description: "LedgerFest is Columbia University’s second blockchain and crypto conference"
baseurl: ""
url: "https://ledgerfest.info"
permalink: "/blog/:title"

# Organizer Info
organizerName: "B@C"
organizerAlternateName: "Blockchain at Columbia"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "blockchain@columbia.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://blockchainatcolumbia.com/"

# Head
metaKeywords: "blockchain, conference"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171"
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/faq/", text: "FAQ"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Register"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Register"}

# Hero Block
heroImage: "cuview.jpg"
heroTitle: "LedgerFest <typeout>"
eventDate: "March 27, 2020"
typeoutTextValues: '"", "2020"'
typeoutFallback: "2020"
heroButtons:
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Register"}
# About Block
aboutTitle: "About LedgerFest"
aboutBlock:
 - {title: "Conference", image: "kadena.jpg", text: "LedgerFest is Columbia University’s second blockchain and crypto conference. Through this conference, B@C aims to introduce students to companies and individuals doing phenomenal work in the distributed ledger environment." }
 - {title: "Topics", image: "hackathon2.jpg", text: "Decentralized finance, industry applications of distributed ledgers, humanitarian and political impact of blockchains and more." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "10", specialCharacter: "", info: "hours", detail: ""}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: ""}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Columbia University, Pupin Hall"
eventLocationLink: "http://www.columbia.edu/cu/computinghistory/pupin.html"
eventStreetAddress: "538 W 120th St"
eventAddressLocality: "New York"
eventAddressLocalityRegion: "New York"
eventPostalCode: "10027"
eventAddressCountry: "U.S"
eventStartTime: "2020-03-27T08:15"
eventDoorTime: "08:45"
eventEndTime: "2020-03-27T18:30"
eventPlaceCoordinates: "40.809984, -73.961386"
mapCenterCoordinates: "40.809984, -73.961386"
mapMobileCenterCoordinates: "40.809984, -73.961386"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_20.jpg"
venueSmallImage1: "venue_21.jpg"
venueSmallImage2: "venue_21.jpg"
venueSmallImage3: "venue_21.jpg"
venueTitle: "Pupin Hall"
venueFeatures: ["Pupin Hall", "Rooms TBA", "538 W 120th St, New York, NY 10027"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "ledgerfest20"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Register"

# Footer
socialLinks:
 - {link: "https://www.instagram.com/blockchaincolumbia/", icon: "linkedin"}
 - {link: "https://twitter.com/blockchainatcu?lang=en", icon: "twitter"}
 - {link: "https://www.facebook.com/BlockchainatColumbia/?ref=bookmarks", icon: "facebook"}
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", icon: "rss"}
 - {link: "https://blockchainatcolumbia.com/", icon: "site"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Evenbrite - LedgerFest Tickets"}
   - {link: "https://blockchainatcolumbia.com/", text: "Blockchain at Columbia"}
   - {link: "http://www.columbia.edu/files/columbia/content/morningsidemap_2013july.pdf", text: "Map"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:blockchain@columbia.edu", text: "blockchain@columbia.edu"}
 -
  title: "FAQ"
  links:
   - {permalink: "/faq/", text: "Frequently Asked Questions"}

# Speakers List Block
showSessions: true
