# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "LedgerFest 2021"
email: "blockchain@columbia.edu"
description: "LedgerFest is Blockchain@Columbia's annual crypto conference."
baseurl: ""
url: "https://ledgerfest.info"
permalink: "/blog/:title"

# Organizer Info
organizerName: "B@C"
organizerAlternateName: "Blockchain at Columbia"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "blockchain@columbia.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://blockchainatcolumbia.org/"

# Head
metaKeywords: "blockchain, conference"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171"
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/faq/", text: "FAQ"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Register"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Register"}

# Hero Block
heroImage: "cuview.jpg"
heroTitle: "LedgerFest <typeout>"
eventDate: "October 22-23, 2021"
typeoutTextValues: '"", "2021"'
typeoutFallback: "2021"
heroButtons:
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Register"}
# About Block
aboutTitle: "About LedgerFest"
aboutBlock:
 - {title: "Conference", image: "conf.jpg", text: "LedgerFest is Blockchain@Columbia's annual crypto conference. We aim to educate and inspire students and the broader community through fireside chats, talks, and tutorials from founders and operators of the leading protocols and investors in the space." }
 - {title: "Topics", image: "hackathon2.jpg", text: "DeFi, web3, layer 1/layer2 research and protocols, NFTs, crypto gaming, humanitarian and political impact of blockchains, and more." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "2", specialCharacter: "", info: "days", detail: ""}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: ""}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Gather"
eventLocationLink: "http://www.columbia.edu/cu/computinghistory/pupin.html"
# eventStreetAddress: ""
# eventAddressLocality: ""
# eventAddressLocalityRegion: ""
eventPostalCode: "10027"
eventAddressCountry: "U.S"
eventStartTime: "2021-10-22T10:00"
eventDoorTime: "08:45"
eventEndTime: "2021-10-23T19:45"
eventPlaceCoordinates: "40.809984, -73.961386"
mapCenterCoordinates: "40.809984, -73.961386"
mapMobileCenterCoordinates: "40.809984, -73.961386"

# Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_20.jpg"
# venueSmallImage1: "venue_21.jpg"
# venueSmallImage2: "venue_21.jpg"
# venueSmallImage3: "venue_21.jpg"
# venueTitle: "Pupin Hall"
# venueFeatures: ["Pupin Hall", "Rooms TBA", "538 W 120th St, New York, NY 10027"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "ledgerfest21"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Register"

# Footer
socialLinks:
 - {link: "https://www.instagram.com/blockchaincolumbia/", icon: "linkedin"}
 - {link: "https://twitter.com/blockchainatcu?lang=en", icon: "twitter"}
 - {link: "https://www.facebook.com/BlockchainatColumbia/?ref=bookmarks", icon: "facebook"}
 - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", icon: "rss"}
 - {link: "https://blockchainatcolumbia.org/", icon: "site"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.eventbrite.com/e/ledgerfest2020-student-blockchain-summit-tickets-97888845171", text: "Evenbrite - LedgerFest Tickets"}
   - {link: "https://blockchainatcolumbia.org/", text: "Blockchain@Columbia"}
   - {link: "http://www.columbia.edu/files/columbia/content/morningsidemap_2013july.pdf", text: "Map"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:blockchain@columbia.edu", text: "blockchain@columbia.edu"}
 -
  title: "FAQ"
  links:
   - {permalink: "/faq/", text: "Frequently Asked Questions"}

# Speakers List Block
showSessions: true
